In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('drug200.csv')

In [3]:
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [4]:
data.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [5]:
X = data[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
print(X[0:5])

[[23 'F' 'HIGH' 'HIGH' 25.355]
 [47 'M' 'LOW' 'HIGH' 13.093]
 [47 'M' 'LOW' 'HIGH' 10.114]
 [28 'F' 'NORMAL' 'HIGH' 7.798]
 [61 'F' 'LOW' 'HIGH' 18.043]]


In [6]:
Y = data[['Drug']].values
print(Y[0:5])

[['drugY']
 ['drugC']
 ['drugC']
 ['drugX']
 ['drugY']]


In [7]:
from sklearn import preprocessing

sex_label = preprocessing.LabelEncoder()
sex_label.fit(['F', 'M'])
X[:, 1] = sex_label.transform(X[:, 1])
print(X[0:5])

[[23 0 'HIGH' 'HIGH' 25.355]
 [47 1 'LOW' 'HIGH' 13.093]
 [47 1 'LOW' 'HIGH' 10.114]
 [28 0 'NORMAL' 'HIGH' 7.798]
 [61 0 'LOW' 'HIGH' 18.043]]


In [8]:
bp_label = preprocessing.LabelEncoder()
bp_label.fit(['LOW', 'NORMAL', 'HIGH'])
X[:, 2] = bp_label.transform(X[:, 2])
print(X[0:5])

[[23 0 0 'HIGH' 25.355]
 [47 1 1 'HIGH' 13.093]
 [47 1 1 'HIGH' 10.114]
 [28 0 2 'HIGH' 7.798]
 [61 0 1 'HIGH' 18.043]]


In [9]:
cholesterol_label = preprocessing.LabelEncoder()
cholesterol_label.fit(['NORMAL', 'HIGH'])
X[:, 3] = cholesterol_label.transform(X[:, 3])
print(X[0:5])

[[23 0 0 0 25.355]
 [47 1 1 0 13.093]
 [47 1 1 0 10.114]
 [28 0 2 0 7.798]
 [61 0 1 0 18.043]]


In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=3)
print("shape of x_train:", x_train.shape)
print("shape of y_train:", y_train.shape)
print("shape of x_test:", x_test.shape)
print("shape of y_test:", y_test.shape)

shape of x_train: (140, 5)
shape of y_train: (140, 1)
shape of x_test: (60, 5)
shape of y_test: (60, 1)


In [11]:
from sklearn.tree import DecisionTreeClassifier
tree_drug = DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [12]:
tree_drug.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [13]:
y_test_ = tree_drug.predict(x_test)
print("real y:\n", y_test[0:5])
print("predicted y:\n", y_test_[0:5])

real y:
 [['drugY']
 ['drugX']
 ['drugX']
 ['drugX']
 ['drugX']]
predicted y:
 ['drugY' 'drugX' 'drugX' 'drugX' 'drugX']


In [14]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_test_)
print("The Score is:", score)

The Score is: 0.9833333333333333
